name: 'npm-multiple-publish'
description: 'Publish multiple packages to multiple registries'
branding:
  icon: align-center
  color: green
inputs:
  tokens:
    description: A list of npm tokens
    required: true
  packageFiles:
    description: A list of package.json files
    required: true
  registries:
    description: A list of registries
    required: true
  dryRun:
    description: Dry Run
    required: false
    default: 'false'
runs:
  using: 'node16'
  main: 'dist/index.js'
  