name: Lint PR
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  label:
    runs-on: ubuntu-latest
    name: Lint PR
    steps:
      - name: label
        uses: action-runner/conventional-labeler@master
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}